from BPLUS_TUPLE import BPLUS_TUPLE
from Funciones import showDatabases
from Funciones import *


def Main():
    tree = BPLUS_TUPLE(3, 2)

    tree.insert([1, "A"])
    tree.insert([2, "B"])
    tree.insert([3, "C"])
    tree.insert([4, "D"])
    tree.insert([5, "E"])
    tree.insert([6, "F"])
    tree.insert([7, "G"])
    tree.insert([8, "H"])

    # Mostrando registros
    print(tree.extractRow([1]))
    print(tree.extractRow([2]))
    print(tree.extractRow([3]))
    print(tree.extractRow([4]))
    print(tree.extractRow([5]))
    print(tree.extractRow([6]))
    print(tree.extractRow([7]))
    print(tree.extractRow([8]))


# Test para funciones
def test():
    print("Creacion de DBs:")
    print(createDatabase('DB1'), end="-")
    print(createDatabase('DB2'), end="-")
    print(createDatabase('DB3'), end="-")
    print(createDatabase('DB4'), end="-")
    print(createDatabase('DB5'))
    print("Impresion de DBs:")
    print(showDatabases())

    # Graficando DBs
    # DataBase.graficar()
    print("\nElimando la DB6:")
    print(dropDatabase('DB6'))
    # DataBase.graficar()

    # Creando Tablas para DB2
    # createTable(database: str, table: str, numberColumns: int)
    print("\nCreacion de Tablas en DBs:")
    print("Creacion Tablas DB2:")
    print(createTable('DB2', 'Table1_DB2', 2), end="-")
    print(createTable('DB2', 'Table2_DB2', 2), end="-")
    print(createTable('DB2', 'Table3_DB2', 2), end="-")
    print(createTable('DB2', 'Table4_DB2', 2), end="-")
    print(createTable('DB2', 'Table5_DB2', 2), end="-")
    print(createTable('DB2', 'Table6_DB2', 2))

    # Creando tablas a DB4
    print("Creacion Tablas DB4:")
    print(createTable('DB4', 'Table1_DB4', 2), end="-")
    print(createTable('DB4', 'Table2_DB4', 2), end="-")
    print(createTable('DB4', 'Table3_DB4', 2), end="-")
    print(createTable('DB4', 'Table4_DB4', 2), end="-")
    print(createTable('DB4', 'Table5_DB4', 2), end="-")
    print(createTable('DB4', 'Table6_DB4', 2))

    # Mostrando las tablas
    # Mostrando Tablas DB2, DB3, DB4
    print("\nMostrando Tablas de DBs:")
    print("Tablas DB2:")
    print(showTables('DB2'))
    print("Tablas DB3 (sin tablas):")
    print(showTables('DB3'))
    print("Tablas DB30 (no existente):")
    print(showTables('DB30'))
    print("Tablas DB4:")
    print(showTables('DB4'))

    print('\nInsertando tuplas en DB4:')
    print(insert('DB4', 'Table1_DB4', ["sddd", "Manuel"]), end='-')
    print(insert('DB4', 'Table1_DB4', [2, "Gabriela"]), end='-')
    print(insert('DB4', 'Table1_DB4', [3, "Diego"]), end='-')
    print(insert('DB4', 'Table1_DB4', [4, "Diego2"]))
    print(insert('DB4', 'Table1_DB4', [5, "Diego3"]))

    print("\nBorrando una columna de Table1_DB4:")
    print(alterDropColumn('DB4', 'Table1_DB4', 0))
    print(alterDropColumn('DB4', 'Table1_DB4', 0))

    print('1. Colocando las llaves primarias con alter')
    print(alterAddPK('DB4', 'Table1_DB4', [1]))

    print('1.2 Eliminando la llave primaria de DB4:')
    print(alterDropPK('DB4', 'Table1_DB4'))

    print('2. Colocando las llaves primarias con alter')
    print(alterAddPK('DB4', 'Table1_DB4', [0, 1]))
    # print("\nGraficando Tablas de DBs")
    # print("Tablas de DB2")
    # print(graficarTablas("DB2"))

def test2():
    print("Creacion de DBs:")
    print(createDatabase('DB1'), end="-")
    print(createDatabase('DB2'), end="-")
    print(createDatabase('DB3'), end="-")
    print(createDatabase('DB4'), end="-")
    print(createDatabase('DB5'), end="-")
    print(createDatabase('DB6'), end="-")
    print(createDatabase('DB7'), end="-")
    print(createDatabase('DB8'), end="-")
    print(createDatabase('DB9'), end="-")
    print(createDatabase('DB10'), end="-")
    print(createDatabase('DB11'), end="-")
    print(createDatabase('DB12'), end="-")
    print(createDatabase('DB13'), end="-")
    print(createDatabase('DB14'), end="-")
    print(createDatabase('DB15'), end="-")
    print(createDatabase('DB16'), end="-")
    print(createDatabase('DB17'), end="-")
    print(createDatabase('DB18'), end="-")
    print(createDatabase('DB19'), end="-")
    print(createDatabase('DB20'), end="-")
    print(createDatabase('DB21'), end="-")
    print(createDatabase('DB22'), end="-")
    print(createDatabase('DB23'), end="-")
    print(createDatabase('DB24'), end="-")
    print(createDatabase('DB25'))
    print(createDatabase('DB26'), end="-")
    print(createDatabase('DB27'), end="-")
    print(createDatabase('DB28'), end="-")
    print(createDatabase('DB29'), end="-")
    print(createDatabase('DB30'), end="-")
    print(createDatabase('DB31'), end="-")
    print(createDatabase('DB32'), end="-")
    print(createDatabase('DB33'), end="-")
    print(createDatabase('DB34'), end="-")
    print(createDatabase('DB35'), end="-")
    print(createDatabase('DB36'), end="-")
    print(createDatabase('DB37'), end="-")
    print(createDatabase('DB38'), end="-")
    print(createDatabase('DB39'), end="-")
    print(createDatabase('DB40'), end="-")
    print(createDatabase('DB41'), end="-")
    print(createDatabase('DB42'), end="-")
    print(createDatabase('DB43'), end="-")
    print(createDatabase('DB44'), end="-")
    print(createDatabase('DB45'), end="-")
    print(createDatabase('DB46'), end="-")
    print(createDatabase('DB47'), end="-")
    print(createDatabase('DB48'), end="-")
    print(createDatabase('DB49'), end="-")
    print(createDatabase('DB50'))
    print(createDatabase('DB51'), end="-")
    print(createDatabase('DB52'), end="-")
    print(createDatabase('DB53'), end="-")
    print(createDatabase('DB54'), end="-")
    print(createDatabase('DB55'), end="-")
    print(createDatabase('DB56'), end="-")
    print(createDatabase('DB57'), end="-")
    print(createDatabase('DB58'), end="-")
    print(createDatabase('DB59'), end="-")
    print(createDatabase('DB60'), end="-")
    print(createDatabase('DB61'), end="-")
    print(createDatabase('DB62'), end="-")
    print(createDatabase('DB63'), end="-")
    print(createDatabase('DB64'), end="-")
    print(createDatabase('DB65'), end="-")
    print(createDatabase('DB66'), end="-")
    print(createDatabase('DB67'), end="-")
    print(createDatabase('DB68'), end="-")
    print(createDatabase('DB69'), end="-")
    print(createDatabase('DB70'), end="-")
    print(createDatabase('DB71'), end="-")
    print(createDatabase('DB72'), end="-")
    print(createDatabase('DB73'), end="-")
    print(createDatabase('DB74'), end="-")
    print(createDatabase('DB75'))
    print(createDatabase('DB76'), end="-")
    print(createDatabase('DB77'), end="-")
    print(createDatabase('DB78'), end="-")
    print(createDatabase('DB79'), end="-")
    print(createDatabase('DB80'), end="-")
    print(createDatabase('DB81'), end="-")
    print(createDatabase('DB82'), end="-")
    print(createDatabase('DB83'), end="-")
    print(createDatabase('DB84'), end="-")
    print(createDatabase('DB85'), end="-")
    print(createDatabase('DB86'), end="-")
    print(createDatabase('DB87'), end="-")
    print(createDatabase('DB88'), end="-")
    print(createDatabase('DB89'), end="-")
    print(createDatabase('DB90'), end="-")
    print(createDatabase('DB91'), end="-")
    print(createDatabase('DB92'), end="-")
    print(createDatabase('DB93'), end="-")
    print(createDatabase('DB94'), end="-")
    print(createDatabase('DB95'), end="-")
    print(createDatabase('DB96'), end="-")
    print(createDatabase('DB97'), end="-")
    print(createDatabase('DB98'), end="-")
    print(createDatabase('DB99'), end="-")
    print(createDatabase('DB100'))

    # print("Impresion de DBs:")
    # print(showDatabases())

    # Graficando DBs
    # DataBase.graficar()
    # print("\nElimando la DB6:")
    # print(dropDatabase('DB6'))
    # DataBase.graficar()

    # Creando Tablas para DB2
    # createTable(database: str, table: str, numberColumns: int)
    print("\nCreacion de Tablas en DBs:")
    print("Creacion Tablas DB2:")
    print(createTable('DB2', 'Table1_DB2', 2), end="-")
    print(createTable('DB2', 'Table2_DB2', 2), end="-")
    print(createTable('DB2', 'Table3_DB2', 2), end="-")
    print(createTable('DB2', 'Table4_DB2', 2), end="-")
    print(createTable('DB2', 'Table5_DB2', 2), end="-")
    print(createTable('DB2', 'Table6_DB2', 2), end="-")
    print(createTable('DB2', 'Table7_DB2', 2), end="-")
    print(createTable('DB2', 'Table8_DB2', 2), end="-")
    print(createTable('DB2', 'Table9_DB2', 2), end="-")
    print(createTable('DB2', 'Table10_DB2', 2), end="-")
    print(createTable('DB2', 'Table11_DB2', 2), end="-")
    print(createTable('DB2', 'Table12_DB2', 2), end="-")
    print(createTable('DB2', 'Table13_DB2', 2), end="-")
    print(createTable('DB2', 'Table14_DB2', 2), end="-")
    print(createTable('DB2', 'Table15_DB2', 2), end="-")
    print(createTable('DB2', 'Table16_DB2', 2), end="-")
    print(createTable('DB2', 'Table17_DB2', 2), end="-")
    print(createTable('DB2', 'Table18_DB2', 2), end="-")
    print(createTable('DB2', 'Table19_DB2', 2), end="-")
    print(createTable('DB2', 'Table20_DB2', 2), end="-")
    print(createTable('DB2', 'Table21_DB2', 2), end="-")
    print(createTable('DB2', 'Table22_DB2', 2), end="-")
    print(createTable('DB2', 'Table23_DB2', 2), end="-")
    print(createTable('DB2', 'Table24_DB2', 2), end="-")
    print(createTable('DB2', 'Table25_DB2', 2))
    print(createTable('DB2', 'Table26_DB2', 2), end="-")
    print(createTable('DB2', 'Table27_DB2', 2), end="-")
    print(createTable('DB2', 'Table28_DB2', 2), end="-")
    print(createTable('DB2', 'Table29_DB2', 2), end="-")
    print(createTable('DB2', 'Table30_DB2', 2), end="-")
    print(createTable('DB2', 'Table31_DB2', 2), end="-")
    print(createTable('DB2', 'Table32_DB2', 2), end="-")
    print(createTable('DB2', 'Table33_DB2', 2), end="-")
    print(createTable('DB2', 'Table34_DB2', 2), end="-")
    print(createTable('DB2', 'Table35_DB2', 2), end="-")
    print(createTable('DB2', 'Table36_DB2', 2), end="-")
    print(createTable('DB2', 'Table37_DB2', 2), end="-")
    print(createTable('DB2', 'Table38_DB2', 2), end="-")
    print(createTable('DB2', 'Table39_DB2', 2), end="-")
    print(createTable('DB2', 'Table40_DB2', 2), end="-")
    print(createTable('DB2', 'Table41_DB2', 2), end="-")
    print(createTable('DB2', 'Table42_DB2', 2), end="-")
    print(createTable('DB2', 'Table43_DB2', 2), end="-")
    print(createTable('DB2', 'Table44_DB2', 2), end="-")
    print(createTable('DB2', 'Table45_DB2', 2), end="-")
    print(createTable('DB2', 'Table46_DB2', 2), end="-")
    print(createTable('DB2', 'Table47_DB2', 2), end="-")
    print(createTable('DB2', 'Table48_DB2', 2), end="-")
    print(createTable('DB2', 'Table49_DB2', 2), end="-")
    print(createTable('DB2', 'Table50_DB2', 2), end="-")

    # Creando tablas a DB4
    print("Creacion Tablas DB4:")
    print(createTable('DB4', 'Table1_DB4', 4), end="-")
    print(createTable('DB4', 'Table2_DB4', 4), end="-")
    print(createTable('DB4', 'Table3_DB4', 4), end="-")
    print(createTable('DB4', 'Table4_DB4', 4), end="-")
    print(createTable('DB4', 'Table5_DB4', 4), end="-")
    print(createTable('DB4', 'Table6_DB4', 4), end="-")
    print(createTable('DB4', 'Table7_DB4', 4), end="-")
    print(createTable('DB2', 'Table8_DB4', 4), end="-")
    print(createTable('DB4', 'Table9_DB4', 4), end="-")
    print(createTable('DB4', 'Table10_DB4', 4), end="-")
    print(createTable('DB4', 'Table11_DB4', 4), end="-")
    print(createTable('DB4', 'Table12_DB4', 4), end="-")
    print(createTable('DB4', 'Table13_DB4', 4), end="-")
    print(createTable('DB4', 'Table14_DB4', 4), end="-")
    print(createTable('DB4', 'Table15_DB4', 4), end="-")
    print(createTable('DB4', 'Table16_DB4', 4), end="-")
    print(createTable('DB4', 'Table17_DB4', 4), end="-")
    print(createTable('DB4', 'Table18_DB4', 4), end="-")
    print(createTable('DB4', 'Table19_DB4', 4), end="-")
    print(createTable('DB4', 'Table20_DB4', 4), end="-")
    print(createTable('DB4', 'Table21_DB4', 4), end="-")
    print(createTable('DB4', 'Table22_DB4', 4), end="-")
    print(createTable('DB4', 'Table23_DB4', 4), end="-")
    print(createTable('DB4', 'Table24_DB4', 4), end="-")
    print(createTable('DB4', 'Table25_DB4', 4))
    print(createTable('DB4', 'Table26_DB4', 4), end="-")
    print(createTable('DB4', 'Table27_DB4', 4), end="-")
    print(createTable('DB4', 'Table28_DB4', 4), end="-")
    print(createTable('DB4', 'Table29_DB4', 4), end="-")
    print(createTable('DB4', 'Table30_DB4', 4), end="-")
    print(createTable('DB4', 'Table31_DB4', 4), end="-")
    print(createTable('DB4', 'Table32_DB4', 4), end="-")
    print(createTable('DB4', 'Table33_DB4', 4), end="-")
    print(createTable('DB4', 'Table34_DB4', 4), end="-")
    print(createTable('DB4', 'Table35_DB4', 4), end="-")
    print(createTable('DB4', 'Table36_DB4', 4), end="-")
    print(createTable('DB4', 'Table37_DB4', 4), end="-")
    print(createTable('DB4', 'Table38_DB4', 4), end="-")
    print(createTable('DB4', 'Table39_DB4', 4), end="-")
    print(createTable('DB4', 'Table40_DB4', 4), end="-")
    print(createTable('DB4', 'Table41_DB4', 4), end="-")
    print(createTable('DB4', 'Table42_DB4', 4), end="-")
    print(createTable('DB4', 'Table43_DB4', 4), end="-")
    print(createTable('DB4', 'Table44_DB4', 4), end="-")
    print(createTable('DB4', 'Table45_DB4', 4), end="-")
    print(createTable('DB4', 'Table46_DB4', 4), end="-")
    print(createTable('DB4', 'Table47_DB4', 4), end="-")
    print(createTable('DB4', 'Table48_DB4', 4), end="-")
    print(createTable('DB4', 'Table49_DB4', 4), end="-")
    print(createTable('DB4', 'Table50_DB4', 4), end="-")

    print("Creacion Tablas DB6:")
    print(createTable('DB6', 'Table1_DB6', 6), end="-")
    print(createTable('DB6', 'Table2_DB6', 6), end="-")
    print(createTable('DB6', 'Table3_DB6', 6), end="-")
    print(createTable('DB6', 'Table4_DB6', 6), end="-")
    print(createTable('DB6', 'Table5_DB6', 6), end="-")
    print(createTable('DB6', 'Table6_DB6', 6), end="-")
    print(createTable('DB6', 'Table7_DB6', 6), end="-")
    print(createTable('DB6', 'Table8_DB6', 6), end="-")
    print(createTable('DB6', 'Table9_DB6', 6), end="-")
    print(createTable('DB6', 'Table10_DB6', 6), end="-")
    print(createTable('DB6', 'Table11_DB6', 6), end="-")
    print(createTable('DB6', 'Table12_DB6', 6), end="-")
    print(createTable('DB6', 'Table13_DB6', 6), end="-")
    print(createTable('DB6', 'Table14_DB6', 6), end="-")
    print(createTable('DB6', 'Table15_DB6', 6), end="-")
    print(createTable('DB6', 'Table16_DB6', 6), end="-")
    print(createTable('DB6', 'Table17_DB6', 6), end="-")
    print(createTable('DB6', 'Table18_DB6', 6), end="-")
    print(createTable('DB6', 'Table19_DB6', 6), end="-")
    print(createTable('DB6', 'Table20_DB6', 6), end="-")
    print(createTable('DB6', 'Table21_DB6', 6), end="-")
    print(createTable('DB6', 'Table22_DB6', 6), end="-")
    print(createTable('DB6', 'Table23_DB6', 6), end="-")
    print(createTable('DB6', 'Table24_DB6', 6), end="-")
    print(createTable('DB6', 'Table25_DB6', 6))
    print(createTable('DB6', 'Table26_DB6', 6), end="-")
    print(createTable('DB6', 'Table27_DB6', 6), end="-")
    print(createTable('DB6', 'Table28_DB6', 6), end="-")
    print(createTable('DB6', 'Table29_DB6', 6), end="-")
    print(createTable('DB6', 'Table30_DB6', 6), end="-")
    print(createTable('DB6', 'Table31_DB6', 6), end="-")
    print(createTable('DB6', 'Table32_DB6', 6), end="-")
    print(createTable('DB6', 'Table33_DB6', 6), end="-")
    print(createTable('DB6', 'Table34_DB6', 6), end="-")
    print(createTable('DB6', 'Table35_DB6', 6), end="-")
    print(createTable('DB6', 'Table36_DB6', 6), end="-")
    print(createTable('DB6', 'Table37_DB6', 6), end="-")
    print(createTable('DB6', 'Table38_DB6', 6), end="-")
    print(createTable('DB6', 'Table39_DB6', 6), end="-")
    print(createTable('DB6', 'Table40_DB6', 6), end="-")
    print(createTable('DB6', 'Table41_DB6', 6), end="-")
    print(createTable('DB6', 'Table42_DB6', 6), end="-")
    print(createTable('DB6', 'Table43_DB6', 6), end="-")
    print(createTable('DB6', 'Table44_DB6', 6), end="-")
    print(createTable('DB6', 'Table45_DB6', 6), end="-")
    print(createTable('DB6', 'Table46_DB6', 6), end="-")
    print(createTable('DB6', 'Table47_DB6', 6), end="-")
    print(createTable('DB6', 'Table48_DB6', 6), end="-")
    print(createTable('DB6', 'Table49_DB6', 6), end="-")
    print(createTable('DB6', 'Table50_DB6', 6), end="-")

    print("Creacion Tablas DB8:")
    print(createTable('DB8', 'Table1_DB8', 8), end="-")
    print(createTable('DB8', 'Table2_DB8', 8), end="-")
    print(createTable('DB8', 'Table3_DB8', 8), end="-")
    print(createTable('DB8', 'Table4_DB8', 8), end="-")
    print(createTable('DB8', 'Table5_DB8', 8), end="-")
    print(createTable('DB8', 'Table6_DB8', 8), end="-")
    print(createTable('DB8', 'Table7_DB8', 8), end="-")
    print(createTable('DB8', 'Table8_DB8', 8), end="-")
    print(createTable('DB8', 'Table9_DB8', 8), end="-")
    print(createTable('DB8', 'Table10_DB8', 8), end="-")
    print(createTable('DB8', 'Table11_DB8', 8), end="-")
    print(createTable('DB8', 'Table12_DB8', 8), end="-")
    print(createTable('DB8', 'Table13_DB8', 8), end="-")
    print(createTable('DB8', 'Table14_DB8', 8), end="-")
    print(createTable('DB8', 'Table15_DB8', 8), end="-")
    print(createTable('DB8', 'Table16_DB8', 8), end="-")
    print(createTable('DB8', 'Table17_DB8', 8), end="-")
    print(createTable('DB8', 'Table18_DB8', 8), end="-")
    print(createTable('DB8', 'Table19_DB8', 8), end="-")
    print(createTable('DB8', 'Table20_DB8', 8), end="-")
    print(createTable('DB8', 'Table21_DB8', 8), end="-")
    print(createTable('DB8', 'Table22_DB8', 8), end="-")
    print(createTable('DB8', 'Table23_DB8', 8), end="-")
    print(createTable('DB8', 'Table24_DB8', 8), end="-")
    print(createTable('DB8', 'Table25_DB8', 8))
    print(createTable('DB8', 'Table26_DB8', 8), end="-")
    print(createTable('DB8', 'Table27_DB8', 8), end="-")
    print(createTable('DB8', 'Table28_DB8', 8), end="-")
    print(createTable('DB8', 'Table29_DB8', 8), end="-")
    print(createTable('DB8', 'Table30_DB8', 8), end="-")
    print(createTable('DB8', 'Table31_DB8', 8), end="-")
    print(createTable('DB8', 'Table32_DB8', 8), end="-")
    print(createTable('DB8', 'Table33_DB8', 8), end="-")
    print(createTable('DB8', 'Table34_DB8', 8), end="-")
    print(createTable('DB8', 'Table35_DB8', 8), end="-")
    print(createTable('DB8', 'Table36_DB8', 8), end="-")
    print(createTable('DB8', 'Table37_DB8', 8), end="-")
    print(createTable('DB8', 'Table38_DB8', 8), end="-")
    print(createTable('DB8', 'Table39_DB8', 8), end="-")
    print(createTable('DB8', 'Table40_DB8', 8), end="-")
    print(createTable('DB8', 'Table41_DB8', 8), end="-")
    print(createTable('DB8', 'Table42_DB8', 8), end="-")
    print(createTable('DB8', 'Table43_DB8', 8), end="-")
    print(createTable('DB8', 'Table44_DB8', 8), end="-")
    print(createTable('DB8', 'Table45_DB8', 8), end="-")
    print(createTable('DB8', 'Table46_DB8', 8), end="-")
    print(createTable('DB8', 'Table47_DB8', 8), end="-")
    print(createTable('DB8', 'Table48_DB8', 8), end="-")
    print(createTable('DB8', 'Table49_DB8', 8), end="-")
    print(createTable('DB8', 'Table50_DB8', 8), end="-")

    print("Creacion Tablas DB10:")
    print(createTable('DB10', 'Table1_DB10', 10), end="-")
    print(createTable('DB10', 'Table2_DB10', 10), end="-")
    print(createTable('DB10', 'Table3_DB10', 10), end="-")
    print(createTable('DB10', 'Table4_DB10', 10), end="-")
    print(createTable('DB10', 'Table5_DB10', 10), end="-")
    print(createTable('DB10', 'Table6_DB10', 10), end="-")
    print(createTable('DB10', 'Table7_DB10', 10), end="-")
    print(createTable('DB10', 'Table8_DB10', 10), end="-")
    print(createTable('DB10', 'Table9_DB10', 10), end="-")
    print(createTable('DB10', 'Table10_DB10', 10), end="-")
    print(createTable('DB10', 'Table11_DB10', 10), end="-")
    print(createTable('DB10', 'Table12_DB10', 10), end="-")
    print(createTable('DB10', 'Table13_DB10', 10), end="-")
    print(createTable('DB10', 'Table14_DB10', 10), end="-")
    print(createTable('DB10', 'Table15_DB10', 10), end="-")
    print(createTable('DB10', 'Table16_DB10', 10), end="-")
    print(createTable('DB10', 'Table17_DB10', 10), end="-")
    print(createTable('DB10', 'Table18_DB10', 10), end="-")
    print(createTable('DB10', 'Table19_DB10', 10), end="-")
    print(createTable('DB10', 'Table20_DB10', 10), end="-")
    print(createTable('DB10', 'Table21_DB10', 10), end="-")
    print(createTable('DB10', 'Table22_DB10', 10), end="-")
    print(createTable('DB10', 'Table23_DB10', 10), end="-")
    print(createTable('DB10', 'Table24_DB10', 10), end="-")
    print(createTable('DB10', 'Table25_DB10', 10))
    print(createTable('DB10', 'Table26_DB10', 10), end="-")
    print(createTable('DB10', 'Table27_DB10', 10), end="-")
    print(createTable('DB10', 'Table28_DB10', 10), end="-")
    print(createTable('DB10', 'Table29_DB10', 10), end="-")
    print(createTable('DB10', 'Table30_DB10', 10), end="-")
    print(createTable('DB10', 'Table31_DB10', 10), end="-")
    print(createTable('DB10', 'Table32_DB10', 10), end="-")
    print(createTable('DB10', 'Table33_DB10', 10), end="-")
    print(createTable('DB10', 'Table34_DB10', 10), end="-")
    print(createTable('DB10', 'Table35_DB10', 10), end="-")
    print(createTable('DB10', 'Table36_DB10', 10), end="-")
    print(createTable('DB10', 'Table37_DB10', 10), end="-")
    print(createTable('DB10', 'Table38_DB10', 10), end="-")
    print(createTable('DB10', 'Table39_DB10', 10), end="-")
    print(createTable('DB10', 'Table40_DB10', 10), end="-")
    print(createTable('DB10', 'Table41_DB10', 10), end="-")
    print(createTable('DB10', 'Table42_DB10', 10), end="-")
    print(createTable('DB10', 'Table43_DB10', 10), end="-")
    print(createTable('DB10', 'Table44_DB10', 10), end="-")
    print(createTable('DB10', 'Table45_DB10', 10), end="-")
    print(createTable('DB10', 'Table46_DB10', 10), end="-")
    print(createTable('DB10', 'Table47_DB10', 10), end="-")
    print(createTable('DB10', 'Table48_DB10', 10), end="-")
    print(createTable('DB10', 'Table49_DB10', 10), end="-")
    print(createTable('DB10', 'Table50_DB10', 10), end="-")

    # Mostrando las tablas
    # Mostrando Tablas DB2, DB3, DB4
    # print("\nMostrando Tablas de DBs:")
    # print("Tablas DB2:")
    # print(showTables('DB2'))
    # print("Tablas DB3 (sin tablas):")
    # print(showTables('DB3'))
    # print("Tablas DB30 (no existente):")
    # print(showTables('DB30'))
    # print("Tablas DB4:")
    # print(showTables('DB4'))

    print('\nInsertando tuplas en DB4:')
    print(insert('DB4', 'Table1_DB4', [1, "Manuel", 0.5, "Azul"]), end='-')
    print(insert('DB4', 'Table1_DB4', [2, "Gabriela", 1.5, "Amarillo"]), end='-')
    print(insert('DB4', 'Table1_DB4', [3, "Diego", 2.5, "Verde"]), end='-')
    print(insert('DB4', 'Table1_DB4', [4, "Antonio", 3.5, "Rosado"]), end='-')
    print(insert('DB4', 'Table1_DB4', [5, "Jorge", 4.5, "Anaranjado"]), end='-')
    print(insert('DB4', 'Table1_DB4', [6, "Mynor", 5.5, "Gris"]), end='-')
    print(insert('DB4', 'Table1_DB4', [7, "Kevin", 6.5, "Celeste"]), end='-')
    print(insert('DB4', 'Table1_DB4', [8, "Aejandro", 7.5, "Blanco"]), end='-')
    print(insert('DB4', 'Table1_DB4', [9, "Nathan", 8.5, "Negro"]), end='-')
    print(insert('DB4', 'Table1_DB4', [10, "Jessica", 9.5, "Rojo"]), end='-')
    print(insert('DB4', 'Table1_DB4', [11, "Ericha", 0.5, "Azul"]), end='-')
    print(insert('DB4', 'Table1_DB4', [12, "Merry", 1.5, "Amarillo"]), end='-')
    print(insert('DB4', 'Table1_DB4', [13, "Sib", 2.5, "Verde"]), end='-')
    print(insert('DB4', 'Table1_DB4', [14, "Violetta", 3.5, "Rosado"]), end='-')
    print(insert('DB4', 'Table1_DB4', [15, "Meghan", 4.5, "Anaranjado"]), end='-')
    print(insert('DB4', 'Table1_DB4', [16, "Heinrick", 5.5, "Gris"]), end='-')
    print(insert('DB4', 'Table1_DB4', [17, "Tiler", 6.5, "Celeste"]), end='-')
    print(insert('DB4', 'Table1_DB4', [18, "Dennie", 7.5, "Blanco"]), end='-')
    print(insert('DB4', 'Table1_DB4', [19, "Dorie", 8.5, "Negro"]), end='-')
    print(insert('DB4', 'Table1_DB4', [20, "Niles", 9.5, "Rojo"]), end='-')
    print(insert('DB4', 'Table1_DB4', [21, "Olag", 0.5, "Azul"]), end='-')
    print(insert('DB4', 'Table1_DB4', [22, "Noland", 1.5, "Amarillo"]), end='-')
    print(insert('DB4', 'Table1_DB4', [23, "Paulita", 2.5, "Verde"]), end='-')
    print(insert('DB4', 'Table1_DB4', [24, "Forrest", 3.5, "Rosado"]), end='-')
    print(insert('DB4', 'Table1_DB4', [25, "Ulrick", 4.5, "Anaranjado"]))
    print(insert('DB4', 'Table1_DB4', [26, "Angil", 5.5, "Gris"]), end='-')
    print(insert('DB4', 'Table1_DB4', [27, "Fiona", 6.5, "Celeste"]), end='-')
    print(insert('DB4', 'Table1_DB4', [28, "Rodrick", 7.5, "Blanco"]), end='-')
    print(insert('DB4', 'Table1_DB4', [29, "Carolyne", 8.5, "Negro"]), end='-')
    print(insert('DB4', 'Table1_DB4', [30, "Cortney", 9.5, "Rojo"]), end='-')
    print(insert('DB4', 'Table1_DB4', [31, "Byron", 0.5, "Azul"]), end='-')
    print(insert('DB4', 'Table1_DB4', [32, "Lazarus", 1.5, "Amarillo"]), end='-')
    print(insert('DB4', 'Table1_DB4', [33, "Cyndy", 2.5, "Verde"]), end='-')
    print(insert('DB4', 'Table1_DB4', [34, "Becca", 3.5, "Rosado"]), end='-')
    print(insert('DB4', 'Table1_DB4', [35, "Brody", 4.5, "Anaranjado"]), end='-')
    print(insert('DB4', 'Table1_DB4', [36, "Darda", 5.5, "Gris"]), end='-')
    print(insert('DB4', 'Table1_DB4', [37, "Patrice", 6.5, "Celeste"]), end='-')
    print(insert('DB4', 'Table1_DB4', [38, "Bay", 7.5, "Blanco"]), end='-')
    print(insert('DB4', 'Table1_DB4', [39, "Giffy", 8.5, "Negro"]), end='-')
    print(insert('DB4', 'Table1_DB4', [40, "Hallsy", 9.5, "Rojo"]), end='-')
    print(insert('DB4', 'Table1_DB4', [41, "Elinor", 0.5, "Azul"]), end='-')
    print(insert('DB4', 'Table1_DB4', [42, "Maitilde", 1.5, "Amarillo"]), end='-')
    print(insert('DB4', 'Table1_DB4', [43, "Van", 2.5, "Verde"]), end='-')
    print(insert('DB4', 'Table1_DB4', [44, "Marcel", 3.5, "Rosado"]), end='-')
    print(insert('DB4', 'Table1_DB4', [45, "Giselle", 4.5, "Anaranjado"]), end='-')
    print(insert('DB4', 'Table1_DB4', [46, "Olympe", 5.5, "Gris"]), end='-')
    print(insert('DB4', 'Table1_DB4', [47, "Roxi", 6.5, "Celeste"]), end='-')
    print(insert('DB4', 'Table1_DB4', [48, "Debbi", 7.5, "Blanco"]), end='-')
    print(insert('DB4', 'Table1_DB4', [49, "Baron", 8.5, "Negro"]), end='-')
    print(insert('DB4', 'Table1_DB4', [50, "Debera", 9.5, "Rojo"]))

    print("\nBorrando una columna de Table1_DB4:")
    print(alterDropColumn('DB4', 'Table1_DB4', 0))
    print(alterDropColumn('DB4', 'Table1_DB4', 0))

    print('1. Colocando las llaves primarias con alter')
    print(alterAddPK('DB4', 'Table1_DB4', [1]))

    print('1.2 Eliminando la llave primaria de DB4:')
    print(alterDropPK('DB4', 'Table1_DB4'))

    print('2. Colocando las llaves primarias con alter')
    print(alterAddPK('DB4', 'Table1_DB4', [0, 1]))
    # print("\nGraficando Tablas de DBs")
    # print("Tablas de DB2")
    # print(graficarTablas("DB2"))



# Main()
test()
